### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by reza35** [aasensio/hazel2#1]
Conda installation did not work for me.  I followed the instructions in  https://aasensio.github.io/hazel2/installation.html.

(rpy3) reza@debian:/data/hazel2$ conda install hazel
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - hazel

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

I could install it via pip but I wonder if one has to activate special branch to install it via conda.

**Comment by aasensio** [comment]
Yes. Conda is still not working. It's written in the manual but it'll come in the next days.
