### ISSUE TITLE
MPI is not working properly

### ISSUE THREAD

**Issue by rahulyadav99** [aasensio/hazel2#10]
My machine has 12 cores. The parallel version is working properly with 4 cores but the following error appears if I use 5 or more cores:
    At line 304 of file src/sir/mreadi2.f
    Fortran runtime error: Bad value during integer read

**Comment by aasensio** [comment]
I cannot reproduce this issue. I'm sure it is related with the gfortran compiler. Every new version of gfortran produces a complete mess, with backward incompatibility. I'll keep this open just in case I find this again.

**Comment by rahulyadav99** [comment]
Now the mpiexec is working properly. Thanks!

**Comment by aasensio** [comment]
Cool.
