### ISSUE TITLE
singularity problem in matrix and SVD did not converge 

### ISSUE THREAD

**Issue by rahulyadav99** [aasensio/hazel2#11]
For some pixels, the code stops due to singularity problem in matrix and SVD non-convergence.

**Comment by aasensio** [comment]
This happens in the Hermite formal solver inside SIR during the iteration. Some models seem to be producing this effect. I'll work on this to output an error code and neglect the pixels for which this happens.

**Comment by aasensio** [comment]
In case this happens, I try the scipy version of SVD with another (more stable) algorithm. I'll keep this open just in case this error keeps appearing.

**Comment by rahulyadav99** [comment]
I have tested the scipy version, it works well. Now there is no SVD convergence problem.

**Comment by aasensio** [comment]
I'll close the issue for the moment.
