### ISSUE TITLE
Not working with all spectral points

### ISSUE THREAD

**Issue by rahulyadav99** [aasensio/hazel2#13]
Hi,
If I trim the spectral points from 185 to 135 (or increase above 200) then I am getting the following error: ValueError: operands could not be broadcast together with shapes (4,140) (1,141).

**Comment by aasensio** [comment]
It is now apparently fixed. I did a few tests and seems like it's working properly with a variety of number of spectral points. I'll keep this open just in case you still see some issues.

**Comment by rahulyadav99** [comment]
The latest version has no such problem. Thanks for fixing this issue.

**Comment by aasensio** [comment]
Great. I close the issue for the moment.
