### ISSUE TITLE
Synthesis with more than 10 chromospheres

### ISSUE THREAD

**Issue by EliseKoo** [aasensio/hazel2#26]
Synthesis with more than 10 chromospheres results in an error.

In Jupyter the error is: 'Jupyter kernel seems to have died'
In VS code the error is: 'Segmentation fault (core dumped)'

**Comment by aasensio** [comment]
Yes, this is a hardcoded limitation, easy to increase if needed. However, in what use case you need to define more than 10 chromospheres?

**Comment by EliseKoo** [comment]
I'm using the code to simulate a planetary atmosphere/transit signal. Since the magnetic field changes quite a lot in the line of sight, I was trying to increase the number of slabs for more accuracy.

**Comment by aasensio** [comment]
Interesting use case. I've updated the maximum number to 100 in the repository. Is this enough for you? If it is higher, I'd need to analyze more in detail the memory consumption. Just pull the repository and recompile the code again.

**Comment by EliseKoo** [comment]
Yes, it works perfectly now! Thank you!
