### ISSUE TITLE
module 'hazel' has no attribute 'Model'

### ISSUE THREAD

**Issue by reza35** [aasensio/hazel2#3]
using the pip installation on a different machine, I can import hazel without problem. now if I follow the instructions in[ Basic usage](https://aasensio.github.io/hazel2/basic.html), 

mod = hazel.Model(working_mode='synthesis'), 

it complains:

AttributeError: module 'hazel' has no attribute 'Model'

**Comment by aasensio** [comment]
pip is still not working. I hope to make it work in the following days.

**Comment by reza35** [comment]
I tried pip again, it installs but for whatever reason does not function properly. So my recommendation is to git clone, and then run the python setup.py install.

**Comment by aasensio** [comment]
Yes. I think it makes sense to distribute to pip once a working version is ready with as many options as possible, at least similar to the original Hazel code in terms of inversions.
